http:
  host: 'localhost'
  port: 3000

db:
  postgres:
    host: 'localhost'
    port: 5432
    profile: 'postgres'
    password: '123456'
    database: 'livelydb'
    entities: "dist/**/**.entity{.ts,.js}"
    logging: true
    migrationsRun: false
    synchronize: true

