version: "3"
services:
  application:
    container_name: offchain
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3101:3100"
    networks:
      - backend
      - devops_infra
    env_file:
      - .env
networks:
  backend:
  devops_infra:
    external: true