version: "3"
services:
  postgres:
    container_name: production_postgres
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - /srv/docker-volumes-data/pgdata:/var/lib/postgresql/data/pgdata:Z
    env_file:
      - .env
    networks:
      - backend_production

  redis:
    container_name: production_redis
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
        - ./deployment_conf/redis/redis.conf:/redis.conf
    command: [ "redis", "/redis.conf" ]
    networks:
      - backend_production

  application:
    container_name: offchain_production
    restart: unless-stopped
    ports:
      - "3101:3100"
    build:
      context: .
      dockerfile: Dockerfile.production
    networks:
      - backend_production
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
networks:
  backend_production: